# -*- coding: utf-8 -*-
"""prediksi_diabetes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Bw0409rYv84npIYIbL3gcPtW3XxpWTm

# Proyek Machine Learning Prediksi Diagnosa Penyakit Diabetes

Sulistyo Chandrianto

# Project Overview

Project machine learning ini dibuat untuk membantu dalam diagnosa penyakit diabetes berdasarkan rekam medis dari pasien.

# Pemahaman Bisnis

## Permasalahan

- Bagaimana membuat model yang dapat memprediksi seorang pasien terkena penyakit diabetes berdasarkan rekam medis ?
- Apa model machine learning yang tepat dan akurat yang dapat digunakan dalam prediksi seseorang terkena penyakit diabetes ?

## Tujuan

- Membuat model machine learning yang dapat memprediksi seorang pasien terkena penyakit diabetes berdasarkan rekam medis.
- Memilih model machine learning yang tepat dan akurat dalam proses memprediksi apakah seorang pasien terkena penyakit diabetes atau tidak.

# Impor Library
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# %matplotlib inline
import seaborn as sns
from sklearn.utils import resample
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import AdaBoostRegressor

"""# Impor Data

Dataset diambil dari [Kaggle Diabetes prediction dataset](https://www.kaggle.com/datasets/iammustafatz/diabetes-prediction-dataset). Data didownload dan dimport ke google colab dengan nama 'diabetest_prediction_dataset.csv'.
"""

file_name = 'diabetes_prediction_dataset.csv'
diabetes_datasets = pd.read_csv(file_name)

"""# Pemahaman Data

## Informasi Data
"""

diabetes_datasets

"""Dari tampilan data ditemukan informasi
- Jumlah data 100.000
- Jumlah kolom 9
"""

diabetes_datasets.info()

"""Terlihat dari informasi jumlah baris di setiap kolom tidak ada value yang hilang. Yang setiap kolom memiliki jumlah baris sebanyak 100.000.

Selain itu, terdapat 5 fitur categorical yaitu gender, smoking_history, hypertension, heart_desease dan diabetes.

> Khusus fitur  hypertension, heart_desease dan diabetes nilai 0 berarti tidak dan 1 berarti iya.

> Dengan diabetes sebagai target fitur.
"""

# unique value fitur gender
diabetes_datasets['gender'].unique()

# unique value fitur smoking_history
diabetes_datasets['smoking_history'].unique()

"""## Eksplore Fitur Univariate"""

# List fitur berdasarkan bagian kategori dan numerik
categorical_features=['gender','smoking_history','hypertension','heart_disease']
numeric_features=['age','bmi','HbA1c_level','blood_glucose_level']

# buat df_numeric untuk memisahkan fitur hypertension dan heart_disease
df_numeric = diabetes_datasets.loc[:, ~diabetes_datasets.columns.isin(categorical_features)]

"""### Fitur Kategorical

#### Fitur gender
"""

feature = categorical_features[0]
count = diabetes_datasets[feature].value_counts()
percent = 100*diabetes_datasets[feature].value_counts(normalize=True)
df = pd.DataFrame({'jumlah sampel':count, 'persentase':percent.round(1)})
print(df)
count.plot(kind='bar', title=feature);

"""Terdapat 3 kategori pada fitur gender yaitu Female, Male dan Other. Perbandingan presentase Female dan Male hampir sama yaitu 58% dan 41% dengan presentase Female lebih besar.

#### Fitur smoking_history
"""

feature = categorical_features[1]
count = diabetes_datasets[feature].value_counts()
percent = 100*diabetes_datasets[feature].value_counts(normalize=True)
df = pd.DataFrame({'jumlah sampel':count, 'persentase':percent.round(1)})
print(df)
count.plot(kind='bar', title=feature);

"""Terdapat 6 kategori di fitur smoking_history, yaitu No Info, never, former, current, not current, ever. Dengan dominasi nilai kategori No Info dan never yang paling besar yaitu dengan presentase masing-masing 35%

### Fitur Numerik
"""

df_numeric.hist(bins=50, figsize=(20,15))
plt.show()

"""Dari histogram di atas ditemukan:
- Pasien berumur 80 tahun paling banyak

## Eksplore Fitur Multivariate

Mencari hubungan antara dua atau lebih fitur data

### Fitur Kategorical
"""

categorical_features

# plot hubungan categorical dengan fitur diabetes
for col in categorical_features:
  sns.catplot(x=col, y="diabetes", kind="bar", dodge=False, height = 4, aspect = 3,  data=diabetes_datasets, palette="Set3")
  plt.title("Rata-rata 'diabetes' Relatif terhadap - {}".format(col))

"""Dari hubungan fitur target diabetes dengan fitur kategorical, didapatkan bahwa :
- pengidap hipertensi memiliki rata-rata terkena penyakit diabetes lebih tinggi
- pengidap sakit jantung memiliki rata-rata terkena penyakit diabetes lebih tinggi
- fitur gender dan smoking_history berpengaruh sedikit ke fitur diabetes

### Fitur Numerik
"""

# Mengamati hubungan antar fitur numerik dengan pairplot()
sns.pairplot(diabetes_datasets, diag_kind = 'kde')

"""Dari pairplot diatas,pada fitur target diabetes ditemukan fitur **HbA1c_level** dan blood_glucose_level mempengaruhi fitur diabetes. Semakin tinggi nilai pada sumbu x semakin tinggi pula probabilitas pasien terkena penyakit diabetes (diabetes=1)"""

# Mengamati hubungan antar fitur numerik dengan heatmap

plt.figure(figsize = (10,8))
sns.heatmap(df_numeric.corr(), annot = True)

"""Dari heatmap diatas dapat disimpulkan korelasi **blood_glucose_level** dan **HbA1c_level** memiliki nilai korelasi yang cukup tinggi


> Hasil dari pairplot dan heatmap memiliki kesamaan yaitu fitur numerik yang berkorelasi tinggi dengan fitur target diabetes adalah **blood_glucose_level** dan **HbA1c_level**

# Persiapan Data

## Menangani Missing Value
"""

# Deskripsi data
diabetes_datasets.describe()

"""Nilai minimal di fitur age bukan 0 sehingga tidak perlu di periksa missing value lagi."""

# Total data kosong di setiap kolom
diabetes_datasets.isna().sum()

"""Tidak ditemukan missing value.

## Menangani Outliers

Menggunakan teknik visualisasi data (boxplot) pada fitur numerik.

Fitur numerik yang akan di periksa adalah
- age
- bmi
- HbA1c_level
- blood_glucose_level
"""

# fitur age
sns.boxplot(x=diabetes_datasets['age'])

# fitur bmi
sns.boxplot(x=diabetes_datasets['bmi'])

# fitur HbA1c_level
sns.boxplot(x=diabetes_datasets['HbA1c_level'])

# fitur blood_glucose_level
sns.boxplot(x=diabetes_datasets['blood_glucose_level'])

# Menghapus dengan metode IQR

Q1 = diabetes_datasets.quantile(0.25)
Q3 = diabetes_datasets.quantile(0.75)
IQR=Q3-Q1
cleaned_df=diabetes_datasets[~((diabetes_datasets<(Q1-1.5*IQR))|(diabetes_datasets>(Q3+1.5*IQR))).any(axis=1)]

# Cek value di fitur target diabetes
cleaned_df['diabetes'].value_counts()

"""Setelah menggunakan metode IQR ternyata nilai 1 di fitur 'diabetes' di hapus semua sehingga tidak dilakukan penghapusan outliers"""

diabetes_datasets

"""## Melakukan Encoding Fitur Kategori

Menerapkan encoding ke fitur kategori dengan teknik OHE (*one-hot-encoding*)
"""

diabetes_datasets = pd.concat([diabetes_datasets, pd.get_dummies(diabetes_datasets['gender'], prefix='gender')],axis=1)
diabetes_datasets = pd.concat([diabetes_datasets, pd.get_dummies(diabetes_datasets['smoking_history'], prefix='smoking_history')],axis=1)

diabetes_datasets.head()

diabetes_datasets.drop(['gender','smoking_history'], axis=1, inplace=True)

diabetes_datasets.head()

"""## Menangani Imbalance Dataset di Fitur Target"""

diabetes_datasets['diabetes'].value_counts()

"""Dapat dilihat diatas bahwa perbandingan nilai di fitur target 'diabetes' sangat timpang yaitu 915:85 atau hampir 10:1

Maka dari itu dilakukan teknik Random Oversampling and Undersampling
"""

# ambil tiap kategori
non_diabetic  = diabetes_datasets[diabetes_datasets['diabetes']==0]
diabetic = diabetes_datasets[diabetes_datasets['diabetes']==1]

# resample data agar perbandingan 1:1
resample_diabetic = resample(diabetic, replace = True, n_samples = 91500)

diabetes_datasets = pd.concat([non_diabetic, resample_diabetic])
diabetes_datasets['diabetes'].value_counts()

# recheck info dataset
diabetes_datasets.info()

"""## Pembagian data latih dan data uji

Membagi dataset menjadi 95% data latih dan 5% data uji agar jumlah data uji tidak terlalu banyak.
"""

X = diabetes_datasets.drop('diabetes',axis=1)
y = diabetes_datasets['diabetes']

# Perbandingan 9.5:0.5
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state = 20)

print(f'Total # of sample in whole dataset: {len(X)}')
print(f'Total # of sample in train dataset: {len(X_train)}')
print(f'Total # of sample in test dataset: {len(X_test)}')

"""## Normalisasi

Menerapkan standarisasi pada data latih untuk menghindari kebocoran data.

Proses standarisasi fitur numerik menggunakan *StandardScaler*  yaitu mengubah rata-rata menjadi 0 dan standard deviasi menjadi 1
"""

scaler = StandardScaler()
scaler.fit(X_train[numeric_features])
X_train[numeric_features] = scaler.transform(X_train.loc[:, numeric_features])
X_train[numeric_features].head()

# Cek nilai rata-rata = 1 dan standar deviasi = 1
X_train[numeric_features].describe().round(4)

"""# Modeling

Model yang digunakan adalah KNN, Random Forest dan Adaptive Boosting.
"""

# datagram untuk analisis model
models = pd.DataFrame(index=['train_mse', 'test_mse'],
                      columns=['KNN', 'RandomForest', 'AdaptiveBoosting'])

"""## KNN (K-Nearest Neigbhor)"""

model_knn = KNeighborsRegressor(n_neighbors=15)
model_knn.fit(X_train, y_train)

models.loc['train_mse','KNN'] = mean_squared_error(y_pred = model_knn.predict(X_train), y_true=y_train)

"""## Random Forest"""

model_rf = RandomForestRegressor(n_estimators=50, max_depth=16, random_state=50, n_jobs=-1)
model_rf.fit(X_train, y_train)

models.loc['train_mse','RandomForest'] = mean_squared_error(y_pred=model_rf.predict(X_train), y_true=y_train)

"""## Adaptive Boosting"""

model_adaptiveboost = AdaBoostRegressor(learning_rate=0.05, random_state=123)
model_adaptiveboost.fit(X_train, y_train)
models.loc['train_mse','AdaptiveBoosting'] = mean_squared_error(y_pred=model_adaptiveboost.predict(X_train), y_true=y_train)

"""# Evaluasi Model"""

# Scaling fitur numerik data uji
X_test.loc[:, numeric_features] = scaler.transform(X_test[numeric_features])

"""Evalusi menggunakan matriks MSE atau *Mean Squared Error*"""

# DataFrame nilai mse data latih dan uji
mse = pd.DataFrame(columns=['train', 'test'], index=['KNN', 'RandomForest', 'AdaptiveBoosting'])

# Buat dictionary untuk setiap algoritma yang digunakan
model_dict = {'KNN': model_knn, 'RandomForest': model_rf, 'AdaptiveBoosting': model_adaptiveboost}

# Hitung Mean Squared Error masing-masing algoritma pada data train dan test
for name, model in model_dict.items():
    mse.loc[name, 'train'] = mean_squared_error(y_true=y_train, y_pred=model.predict(X_train))
    mse.loc[name, 'test'] = mean_squared_error(y_true=y_test, y_pred=model.predict(X_test))

# Tampilkan mse
mse

# plot
fig, ax = plt.subplots()
mse.sort_values(by='test', ascending=False).plot(kind='barh', ax=ax, zorder=3)
ax.grid(zorder=0)

"""Dari gambar di atas, model Random Forest memiliki nilai error yang paling kecil sehingga model Random Forest akan dipilih sebagai model terbaik untuk diagnosa penyakit diabetes berdasarkan rekam medis pasien.

# Penutup

Model untuk diagnosa penyakit diabetes sudah dibuat dan model ini dapat dikembangkan lagi agar bisa digunakan atau dipasang di aplikasi dengan data sesungguhnya.

Pastinya dibutuhkan pengembangan dan penyempurnaan di model machine learning agar model lebih akurat dalam proses diagnosa.
"""